const SAGA_CHECKTOKEN = 'SAGA_CHECKTOKEN';
const ACTION_CHECKTOKEN = 'ACTION_CHECKTOKEN';
const ACTION_CHECKTOKEN_FAIL = 'ACTION_CHECKTOKEN_FAIL';

export const saga = {
    SAGA_CHECKTOKEN
};

export const action = {
    ACTION_CHECKTOKEN,
    ACTION_CHECKTOKEN_FAIL
};
